enum QuestionCategory {
  TECHNICAL_SUPPORT = "TECHNICAL_SUPPORT",
  PRODUCT_INQUIRIES = "PRODUCT_INQUIRIES",
  ACCOUNT_ASSISTANCE = "ACCOUNT_ASSISTANCE",
  TROUBLESHOOTING = "TROUBLESHOOTING",
  FEEDBACK_SUGGESTIONS = "FEEDBACK_SUGGESTIONS",
  OTHER = "OTHER",
}

export { QuestionCategory }